### PR TITLE
Support Python 3 builds

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by aplanas** [comment]
Alternative from https://github.com/mozilla/python-spidermonkey/pull/9. This one do not needs tests adjustments, as is decoding to UTF-8 by default.

**Comment by aplanas** [comment]
Looks like that Python 2 and <=3.5 do not provide this attribute in the constructor

**Comment by wagnerand** [comment]
Thank you for this pull-request. Are you using this project directly?

**Comment by aplanas** [comment]
I am using it in a project, yes. Is there any recommended alternative? I found python-spidermonkey very easy to integrate in my Python 2 project, and as I am now updating to Python 3 I was thinking to still use it.

**Comment by wagnerand** [comment]
I am not aware of any Mozilla projects using it, other than the one we recently deprecated (https://github.com/mozilla/amo-validator) and I am not sure whether we will keep supporting this project.

@EnTeQuAk might have an opinion on this, he will be back next week.

**Comment by aplanas** [comment]
Ah good to know then. Feel free to close the PR. I will use my fork or find another alternative.

Thanks!

**Comment by aplanas** [comment]
Hi, any news about this PR? If python-spidermonkey is finally deprecated I would happily maintain it on pypi.

**Comment by EnTeQuAk** [comment]
Hey, I'm still following up the last few weeks PTO and conferences. Thank you so much for this pull request! Although we officially deprecated `amo-validator` we are still using it, potentially till fall this year so I'm happy to maintain this project till then at least.

But more contributors are always great so I'll start a discussion to see to add you as a contributor in case you'd be happy to do that. Tha way we can avoid forking the project and simply continue to support it.

**Comment by aplanas** [comment]
> I'll start a discussion to see to add you as a contributor in case you'd be happy to do that. That way we can avoid forking the project and simply continue to support it.

Sure, avoid forking is much better.

**Comment by aplanas** [comment]
Hi,

any decision about this? I can rebase the PR and use a newer version of spidermonkey, if there is version that is recommended.

**Comment by EnTeQuAk** [comment]
We're officially deprecating this library and don't intend to maintain it.

I'm really grateful for your pull request and sorry for the delayed discussion and decision about this. For various reasons we do think that a fork would work best for the community and should maintain better update behaviour for existing users.

I'm going to close this pull request.

**Pull request closed without merging**
